scalar Date
scalar Number

type Machine {
  id: Number!
  name: String!
  sensors: [Sensor!]
  lastKnownPosition: GPSPosition
}

type GPSPosition {
  lat: String
  long: String
}
type Sensor {
  id: Number!
  name: String!
  machine: Machine!
}

type SensorDataPoint {
  id: Number!
  timestamp: Date!
  value: Float!
}

type Query {
  machine(id: Number!): [Machine]
  machines: [Machine!]
  sensorData(id: Number!, from: Date!, to: Date!): [SensorDataPoint]
}

type Mutation {
  addMachine(name: String): Machine
}
