type Machine {
  name: String!
  sensors: [Sensor!]
  lastKnownPosition: GPSPosition
}

type Sensor {
  name: String!
  machine: Machine!
}

type SensorDataPoint {
  timestamp: DateTime!
  value: Float!
}

type Query {
  machine(where: ID!): Machine
  machines: [Machine!]
  sensorData(id: ID!, from: DateTime!, to: DateTime!): [SensorDataPoint]
}

type Mutation {
  addMachine(name: String): Machine
}
