scalar Date

type Machine {
  name: String!
  sensors: [Sensor!]
  lastKnownPosition: GPSPosition
}

type GPSPosition {
  lat: String
  log: String
}
type Sensor {
  name: String!
  machine: Machine!
}

type SensorDataPoint {
  timestamp: Date!
  value: Float!
}

type Query {
  machine(where: ID!): Machine
  machines: [Machine!]
  sensorData(id: ID!, from: Date!, to: Date!): [SensorDataPoint]
}

type Mutation {
  addMachine(name: String): Machine
}
